### ISSUE TITLE
Long Running Service will be supported ? 

### ISSUE THREAD

**Issue by Hyvi** [recode-sh/cli#6]
I Want to run my web server by recode, But It will be supported ?

**Comment by jeremylevy** [comment]
Hey Hyvi! 👋 

I'm not really sure what you mean.

Do you want to be able to have long running processes (i.e. not tied to any terminal) to deploy your app through Recode?

If so, you may also need a fixed public IP address and a way to open ports for your instance to be reachable.

Is that right?

**Comment by Hyvi** [comment]
Thanks for your reply. Yes, i have static public ip and port,but how I run a long running process (such node server) through recode? Hope your reply

**Comment by jeremylevy** [comment]
Re,

This feature is not yet implemented in Recode, so you need to find a workaround.

As an example, I've created a file named `app.js` that contains the following code:

```js
const http = require('http');

const hostname = '0.0.0.0'; // You need to bind to '0.0.0.0' not 'localhost' or '127.0.0.1'
const port = 80;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```
If you want to run this code as a long-running process, do the following:

1. First, open a new terminal using VSCode or SSH.

2. Optionally, **if you need to bind to ports < 1024**, run: 

```bash
echo "net.ipv4.ip_unprivileged_port_start=0" | sudo tee /etc/sysctl.conf > /dev/null
```

and 

```bash
sudo sysctl --system
```

3. Finally, run your app using the following command:

```bash
nohup node app.js &
```

And voilà!

**Comment by Hyvi** [comment]
thanks for your detail explanation.

**Comment by jeremylevy** [comment]
Hey Hyvi! 

Hope you're well. 

I  built a fork of Recode with built-in ports management, long-running processes and HTTPS, that will probably better suits your needs.

If you want to give it a try, it's here: https://github.com/eleven-sh/cli
